# Generated by Django 2.2.5 on 2019-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi', '0002_auto_20190905_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='team',
            name='github',
        ),
        migrations.RemoveField(
            model_name='team',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='team',
            name='ins',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='ln',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_class',
            field=models.CharField(choices=[('Faculty Coordinator', 'Faculty Coordinator'), ('President', 'President'), ('Vice-President', 'Vice-President'), ('Secretary', 'Secretary'), ('Technical Head', 'Technical Head'), ('Chief-Treasurer', 'Chief-Treasurer'), ('Treasurer', 'Treasurer'), ('Reception Incharge', 'Reception Incharge'), ('Event Coordinator', 'Event Coordinator'), ('Coordinator', 'Coordinator'), ('Chief Editor', 'Chief Editor'), ('Editor', 'Editor'), ('Discipline Coordinator', 'Discipline Coordinator'), ('Refreshment Incharge', 'Refreshment Incharge'), ('Class Representative', 'Class Representative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_url',
            field=models.CharField(blank=True, default='#', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
