# Generated by Django 2.2.5 on 2019-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi', '0004_homebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='id',
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
