# Generated by Django 2.2.5 on 2019-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi', '0005_auto_20190918_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='banner_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
