# Generated by Django 2.2.5 on 2019-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi', '0006_homebanner_banner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='sub_head',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
