# Generated by Django 2.2.5 on 2019-09-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi', '0007_auto_20190918_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_class',
            field=models.CharField(choices=[('Dean Engineering', 'Dean Engineering'), ('Head of Department-CSE', 'Head of Department-CSE '), ('Faculty Coordinator', 'Faculty Coordinator'), ('President', 'President'), ('Vice-President', 'Vice-President'), ('Secretary', 'Secretary'), ('Technical Head', 'Technical Head'), ('Chief-Treasurer', 'Chief-Treasurer'), ('Treasurer', 'Treasurer'), ('Reception Incharge', 'Reception Incharge'), ('Event Coordinator', 'Event Coordinator'), ('Coordinator', 'Coordinator'), ('Chief Editor', 'Chief Editor'), ('Editor', 'Editor'), ('Discipline Coordinator', 'Discipline Coordinator'), ('Refreshment Incharge', 'Refreshment Incharge'), ('Class Representative', 'Class Representative')], max_length=50),
        ),
    ]
